name: SciKnowEval-main
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - ca-certificates=2024.3.11
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.18.1
  - jedi=0.19.1
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
# - ld_impl_linux-64=2.38
  - ld_impl_win-64
  - libffi=3.4.4
# - libgcc-ng=13.2.0
  - libgcc
  - libgomp=13.2.0
  - libsodium=1.0.18
# - libstdcxx-ng=11.2.0
  - libstdcxx
  - matplotlib-inline=0.1.6
# - ncurses=6.4
  - m2-ncurses
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.9.19
  - python_abi=3.9
  - pyzmq=25.1.2
# - readline=8.2
  - pyreadline=2.1
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.4
  - traitlets=5.14.2
  - typing_extensions=4.11.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.4
      - aiosignal==1.3.1
      - albumentations==1.4.3
      - annotated-types==0.6.0
      - anyio==4.3.0
      - appdirs==1.4.4
      - argparse==1.4.0
      - arxivcheck==0.3.2
      - asn1crypto==1.5.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - bibtexparser==1.4.1
      - blis==0.7.11
      - blobfile==2.1.1
      - bs4==0.0.2
      - cachetools==5.3.3
      - catalogue==2.0.10
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.16.0
      - colorama==0.4.6
      - confection==0.1.4
      - contourpy==1.2.1
      - cryptography==42.0.5
      - cycler==0.12.1
      - cymem==2.0.8
      - dataclasses-json==0.6.4
      - datasets==2.18.0
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - doi2bib==0.4.0
      - et-xmlfile==1.1.0
      - evals==2.0.0
      - feedparser==6.0.11
      - filelock==3.13.4
      - fire==0.6.0
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - future==1.0.0
      - gast==0.5.4
      - gensim==4.3.2
      - getarticle==0.1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-ai-generativelanguage==0.6.1
      - google-api-core==2.18.0
      - google-api-python-client==2.125.0
      - google-auth==2.29.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.5.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.63.0
      - greenlet==3.0.3
      - grpcio==1.62.1
      - grpcio-status==1.62.1
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httpx==0.27.0
      - huggingface-hub==0.22.2
      - idna==3.7
      - imageio==2.34.0
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - ipdb==0.13.13
      - jinja2==3.1.3
      - jiwer==3.0.3
      - joblib==1.4.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - keras==3.2.1
      - kiwisolver==1.4.5
      - langchain==0.1.16
      - langchain-community==0.0.32
      - langchain-core==0.1.42
      - langchain-text-splitters==0.0.1
      - langcodes==3.3.0
      - langdetect==1.0.9
      - langsmith==0.1.45
      - lazy-loader==0.4
      - levenshtein==0.25.1
      - libclang==18.1.1
      - lightning==2.2.1
      - lightning-utilities==0.11.2
      - lxml==4.9.4
      - lz4==4.3.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.1
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mock==5.1.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - munch==4.0.0
      - murmurhash==1.0.10
      - mypy==1.9.0
      - mypy-extensions==1.0.0
      - namex==0.0.7
      - networkx==3.2.1
      - nltk==3.8.1
      - nougat-ocr==0.1.17
      - numexpr==2.10.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - openai==0.28.1
      - opencv-python-headless==4.9.0.80
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - optree==0.11.0
      - orjson==3.10.0
      - outcome==1.3.0.post0
      - packaging==23.2
      - pandas==2.2.2
      - patsy==0.5.6
      - pillow==10.3.0
      - pluggy==1.4.0
      - portalocker==2.8.2
      - preshed==3.0.9
      - proto-plus==1.23.0
      - protobuf==4.25.3
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pycryptodomex==3.20.0
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pyjwt==2.8.0
      - pymupdf==1.24.1
      - pymupdfb==1.24.1
      - pyopenssl==24.1.0
      - pyparsing==3.1.2
      - pypdf==4.2.0
      - pypdf2==3.0.1
      - pypdfium2==4.29.0
      - pysocks==1.7.1
      - pytest==8.1.1
      - python-dateutil==2.9.0.post0
      - python-levenshtein==0.25.1
      - pytorch-lightning==2.2.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzstd==0.15.10
      - rapidfuzz==3.8.1
      - regex==2023.12.25
      - requests==2.31.0
      - rich==13.7.1
      - rsa==4.9
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - sacrebleu==2.4.1
      - safetensors==0.4.2
      - sciassess==0.9.1
      - scikit-image==0.22.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - sconf==0.2.5
      - seaborn==0.13.2
      - selenium==4.19.0
      - sentence-transformers==2.6.1
      - sentencepiece==0.2.0
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - sgmllib3k==1.0.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - snowflake-connector-python==3.8.1
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spacy==3.7.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spacy-universal-sentence-encoder==0.4.6
      - sqlalchemy==2.0.29
      - srsly==2.4.8
      - statsmodels==0.14.1
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.1
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.36.0
      - termcolor==2.4.0
      - tf-keras==2.16.0
      - thinc==8.2.3
      - threadpoolctl==3.4.0
      - tifffile==2024.2.12
      - tiktoken==0.6.0
      - timm==0.5.4
      - title2bib==0.4.1
      - tokenizers==0.15.2
      - tomli==2.0.1
      - tomlkit==0.12.4
      - torch==2.2.2
      - torchmetrics==1.3.2
      - torchvision==0.17.2
      - tqdm==4.66.2
      - transformers==4.38.2
      - trio==0.25.0
      - trio-websocket==0.11.1
      - triton==2.2.0
      - typer==0.9.4
      - types-pyyaml==6.0.12.20240311
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - unidecode==1.3.8
      - uritemplate==4.1.1
      - urllib3==1.26.18
      - wandb==0.16.6
      - wasabi==1.1.2
      - weasel==0.3.4
      - werkzeug==3.0.2
      - wrapt==1.16.0
      - wsproto==1.2.0
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.18.1