task: generate_answer
gpus: [0]
exp_name: 'gpt-4-turbo-preview'

data_dir:  E:/SciKnowEval_main/results/generate_questions/medical
result_dir: E:/SciKnowEval_main/results

model: gpt-4-turbo-preview
api_base: https://api.ai-gaochao.cn/v1