task: generate_prompts
gpus: [0]
exp_name: 'L2_med'

result_dir: E:/SciKnowEval_main/results
text_dir: E:/SciKnowEval_main/results/extract_pdfs/pypdf2

model: gpt-4o-mini
api_base: https://api.ai-gaochao.cn/v1
max_tokens: 4096
temperature: 0.7
top_p: 0.9
api_batch: 100

num: 2000
length: 1000
